#!/usr/bin/env php
<?php

require_once '../_config.php';

$client = new \Sirprize\Rest\Client();
$responseHandler = new \Sirprize\Rest\ResponseHandler\Dom();

require_once 'Zend/Uri.php';
$uri = \Zend_Uri::factory('http://example.com');

$response = $client->get($responseHandler, $uri);
print $response->getHttpResponse()->getBody();