#!/usr/bin/env php
<?php

require_once '../_config.php';

$client = new \Sirprize\Rest\Client();

$client
	->getHttpClient()
	->resetParameters(true)
	->setUri(\Zend_Uri::factory('http://example.com/target.php')) // this should point to a www-hosted target.php
	->setParameterPost(array('aa' => 'AA'))
	->setHeaders(array())
;

$response = $client->post(new \Sirprize\Rest\ResponseHandler());
print $response->getHttpResponse()->getBody();